#ifndef ZVALUES_H
#define ZVALUES_H

#define ZVALUE_WENDEPUNKT 102
#define ZVALUE_FAHRSTRASSE_AUFLOESEN_MARKERS 101
#define ZVALUE_MARKERS 100
#define ZVALUE_TRAINS 99
#define ZVALUE_FAHRSTRASSESEGMENTS 1
#define ZVALUE_TRACK 0
#define ZVALUE_ARROWS -1

#endif // ZVALUES_H
